#!/usr/bin/env bash
# Display usage if fewer than 4 parameters are passed
if [ "$#" -lt 4 ]; then
	    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	        exit 1
fi

# Assign parameters to variables
FILE_PATH="$1"
SERVER_IP="$2"
USERNAME="$3"
SSH_KEY_PATH="$4"

# Transfer the file using scp with strict host key checking disabled.
scp -o StrictHostKeyChecking=no -i "$SSH_KEY_PATH" "$FILE_PATH" "$USERNAME@$SERVER_IP":~/ 

# Check the exit status of scp
if [ "$?" -eq 0 ]; then
	    echo "File transfer successful!"
    else
	        echo "File transfer failed."
fi 
