#!/usr/bin/env bash
# Bash script that  uses ssh to connect to your server using the private key ~/.ssh/school
ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ubuntu@52.91.202.143
