#!/usr/bin/env bash
# fix nginx listening on port 80

cd /etc/nginx/sites-enabled/ || exit;
# remove default file
rm default;
# make link for sites-available
ln -s /etc/nginx/sites-available/default default
# Restart Nginx
service nginx restart

