#!/usr/bin/env bash
# This script displays a list of currently running processes.

# Use the ps command to list processes with user-oriented format and process hierarchy
ps -e -o user,pid,%cpu,%mem,vsz,rss,tty,stat,start,time,command --forest
