#!/usr/bin/env bash
# This script stops the 4-to_infinity_and_beyond process without using kill.

# Use pkill to send the SIGTERM signal to the 4-to_infinity_and_beyond process
pkill -TERM -f "4-to_infinity_and_beyond"
