#!/usr/bin/env bash
# This script displays "Best School" 10 times using a while loop

# To initialize a counter
count=0

# Use a while loop to display "Best School" until the counter reaches 10
while [ "$count" -lt 10 ]
do
    echo "Best School"
    
    # Increment the counter
    ((count++))
done
