#!/usr/bin/env bash
# Now the script loops from 1 to 10 then displays messages based on the iteration number.

# Initialize a counter
count=1

# Use a while loop to iterate from 1 to 10
while [ "$count" -le 10 ]
do
    # Use if, elif, and else statements to display messages based on the iteration number
    if [ "$count" -eq 4 ]; then
        echo "bad luck"
    elif [ "$count" -eq 8 ]; then
        echo "good luck"
    else
        echo "Best School"
    fi

    # To increment the counter
    ((count++))
done
