#!/usr/bin/env bash
# short fix with instructions
sed -i 's/user nginx;/user root;/' /etc/nginx/nginx.conf
sed -i 's/listen 80 default_server;/listen 8080 default_server;/' /etc/nginx/sites-available/default
service nginx restart
