#!/usr/bin/env bash
# This script connects to the server using SSH and a private key
#private_key_path="/e/ALX projects Personal Training/python/alx-system_engineering-devops/0x0B-ssh/school"
#ssh -i "$private_key_path" ubuntu@52.86.145.36
#!/usr/bin/env bash
# This script connects to the server using SSH and a private key
ssh -i /e/ALX\ projects\ Personal\ Training/python/alx-system_engineering-devops/0x0B-ssh/school -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ubuntu@52.86.145.36
