#!/usr/bin/env bash
# This script connects to the server using SSH and a private key

# Set the correct path to your private key
private_key_path="/e/ALX projects Personal Training/python/alx-system_engineering-devops/0x0B-ssh/school"

# Using ssh with the private key and connecting to the user ubuntu on the server
ssh -i "$private_key_path" ubuntu@52.86.145.36
