#!/usr/bin/env bash
# This script generates ssh key pairs.

# Generate RSA key pair without passphrase
ssh-keygen -b 4096 -f school

# Add passphrase to the private key
ssh-keygen -p -P "" -N "betty" -f school
