#!/bin/bash
# Bash script to generate an RSA key pair with specific requirements

# Set the key file name
KEY_FILE="school"

# Number of bits in the created key
BITS=4096

# Passphrase for the key
PASSPHRASE="betty"

# Generate RSA key pair
ssh-keygen -b $BITS -N "$PASSPHRASE" -f $KEY_FILE

echo "RSA key pair generated successfully."
