#!/bin/bash

# Specify the key name and number of bits
KEY_NAME="school"
BITS=4096

# Ask for a passphrase
read -sp "Enter passphrase for the key: " PASSPHRASE
echo

# Generate the SSH key pair
ssh-keygen -t rsa -b "$BITS" -f "$KEY_NAME" -N "$PASSPHRASE"

# Provide information about the generated key pair
echo "Generating public/private rsa key pair."
echo "Your identification has been saved in $KEY_NAME."
echo "Your public key has been saved in $KEY_NAME.pub."
echo "The key fingerprint is:"
ssh-keygen -l -f "$KEY_NAME"
echo "The key's randomart image is:"
ssh-keygen -l -f "$KEY_NAME" -v -E md5

